# Site
name: 'TrumpTribune'
description: 'Conservative Blog & Conservative News Source for Right of Center Activists'
logo: 'assets/images/logo.png'
favicon: 'assets/images/favicon.ico'
baseurl: ''
disqus: 'TrumpTribune'
email: 'patric.algo@gmail.com'
mailchimp-list: 'https://wowthemes.us11.list-manage.com/subscribe/post?u=8aeb20a530e124561927d3bd8&amp;id=8c3d2d214b'

include: ["_pages"]
permalink: /:title/

# Plugins
plugins: 
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-seo-tag
  
authors:
    Andrew Malcolm:
      name:           Andrew Malcolm
      site:           https://blog.trumptribune.com/
      avatar:         /assets/images/avatar1.png
      bio:            Andrew is a veteran national and foreign correspondent who has covered news and politics since 1968. He spent almost a decade as Communications Director for the governor of Montana, then as Deputy Communications Manager of the first George W. Bush presidential campaign and Laura Bush's press secretary. He's the father of three boys and author of 10 nonfiction books, two of which became movies. Among other posts at RedState, he writes two Malcolm on the Right weekly features -- national politics columns and audio commentaries on whatever. A California escapee, Malcolm is the longtime Tuesday co-host of The Ed Morrissey Show at sister site HotAir.com and now resides in the mountains of Tennessee with his editor wife and their stubborn Border Collie.
      email:          contact@trumptribune.com
      twitter:        https://twitter.com/AHMalcolm

    Bob Hoge:
      name:           Bob Hoge
      site:           https://blog.trumptribune.com/
      avatar:         /assets/images/avatar2.png
      bio:            Bob Hoge is a RedState contributor, proud father and small-business owner.  He is shown sporting his Covid beard, which his wife has since forced him to shave.
      email:          contact@trumptribune.com
      twitter:        https://twitter.com/Bob_Hoge_CA
    
    Alex Parker:
      name:           Alex Parker
      site:           https://blog.trumptribune.com/
      avatar:         /assets/images/avatar3.jpeg
      bio:            
      email:          contact@trumptribune.com
      twitter:        https://twitter.com/#
 
# Defaults
defaults:

  # all posts
  - scope:
      path: "_posts"
    values:
      layout: post
      author: lex Parker
      avatar: /assets/images/avatar3.jpeg
      
  # all pages
  - scope:
      path: "_pages"
    values:
      layout: page
      
# Syntax
markdown: kramdown
highlighter: rouge

# Paginate
paginate: 10



# Exclude metadata and development time dependencies (like Grunt plugins)
exclude: [README.markdown, package.json, grunt.js, Gruntfile.js, Gruntfile.coffee, node_modules]
